version: '3.1'
services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Senha123
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: Senha123
      MYSQL_DATABASE: app
    volumes:
      - ./database/db-dump:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 80:80
    environment:
      - PMA_ARBITRARY=1
